apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot
  namespace: llmobs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
        - name: chatbot
          image: atharv19/inferscope-chatbot:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: llmobs-config
            - secretRef:
                name: llmobs-secrets
          ports:
            - containerPort: 8082
          readinessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 10
